### ISSUE TITLE
Fix doc links to GLib and Gio

### ISSUE THREAD

**Issue by dlech** [ev3dev/grx#2]
For example, links go Gio point to `http://www.ev3dev.org/gio/`. Example `GApplication` on http://www.ev3dev.org/gio/GApplication.html#GApplication-struct.

How do we tell gtkdoc to redirect these to gnome.org?

@ensonic, maybe you know something about this. :smiley:

**Comment by ensonic** [comment]
You can run `gtkdoc-rebase --online --html-dir=/path/to/local/docs` to rewrite the external links.

**Comment by dlech** [comment]
Thanks!

Fixed in https://github.com/dlech/vala-cmake-modules/commit/1600d3b571057d8c558f0975e76e0ac5e3c1d6e2.
